### ISSUE TITLE
websockets / socket.io

### ISSUE THREAD

**Issue by kensac** [kensac/api-rust#26]
[https://github.com/Totodore/socketioxide](https://github.com/Totodore/socketioxide)

Found this and this looks like a suitable solution to implement websockets. Will have to look at how v3 uses ws and then figure out how to port that implementation

**Comment by jdurrell** [comment]
This looks like a useful implementation since it has support for rooms out of the box. As I recall, v3's usage of websockets was primarily for pushing updates to the website and mobile apps about events that have been changed (basically, telling them to flush their cache and re-request for last-minute changes on the day-of).

**Comment by kensac** [comment]
Update comment
Set up sockets and rooms for the API. They can now handle pings from the mobile app and admin pings. Refactored the auth to now give everyone above mentioned threshold access instead of having to explicitly give everyone permission. the sockets can also be accessed through the app state so they can send messages to all clients in the room.
 (Maybe we should also make an ENUM with the possible rooms so that that would reduce future dev errors?)

A slight inefficiency in auth for sockets exists when we ping:admin. This needs to be fixed by either running the two requests and awaiting both to be fulfilled simultaneously or modifying the socket permission check to return a enum with the right permission level that can then be processed by the statement below (better choice as that will reduce our DB / Firebase calls).

```
if permission_check_socket(headers.clone(), Role::Exec).await {
                socket.join(Rooms::Exec.to_string()).ok();
}
if permission_check_socket(headers.clone(), Role::Team).await {
                socket.join(Rooms::Admin.to_string()).ok();
}
```

**Comment by kensac** [comment]
On second thought, will not fix last issue. While inefficient, we need permission_check_socket to be modular for roles other than admin and exec role. Created a struct for room consts that can now be used
